namespace Shared.Bazaar.Enums
{
    // Parse e_info item to see if SpCardBox are empty or not
    public enum SpecialistSub : byte
    {
        All,
        SpCardEmpty,
        Crusader,
        Berseker,
        Warrior,
        Ninja,
        WildKeeper,
        Assassin,
        Destroyer,
        Ranger,
        HolyMage,
        DarkGunner,
        RedMagician,
        BlueMagician,
        Jajamaru,
        Pirate = 17,
        Gladiator,
        FireCannoneer,
        Volcano,
        BattleMonk,
        Scout,
        TideLord,
        DeathReaper,
        DemonHunter,
        Seer,
        Renegade,
        Avenging,
        Archmage,
        DraconicFist,
        MysticArts = 32,
        WeddingCostum,
        MasterWolf,
        DemonWarrior,
        Angler,
        CookingChef = 39,
        Waterfall,
        Sunchaser,
        VoodooPriest,
        FlameDruid,
        DragonKnight = 46,
        Blaster,
        Gravity,
        HydraulicFist,
        PetTrainer
    }
}